# Generated by Django 2.2.7 on 2019-11-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('scientific_name', models.CharField(max_length=100)),
                ('average_lifespan', models.IntegerField()),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('facts', models.CharField(blank=True, max_length=300)),
                ('diet', models.CharField(choices=[('HE', 'Herbivore'), ('OM', 'Omnivore'), ('CA', 'Carnivore')], default='OM', max_length=2)),
            ],
        ),
    ]
