# Generated by Django 2.2.7 on 2019-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scientific_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
