# Generated by Django 2.2.7 on 2019-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20191113_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('yearly_average_rainfall', models.CharField(max_length=50)),
                ('average_temperature', models.CharField(max_length=50)),
                ('plant_types', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='habitats',
            field=models.ManyToManyField(related_name='animals', to='animals.Habitat'),
        ),
    ]
