# Generated by Django 2.2.7 on 2019-11-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_classification_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
