# Generated by Django 2.2.7 on 2019-11-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20191113_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='threats',
            field=models.ManyToManyField(blank=True, related_name='habitats', to='animals.Threat'),
        ),
    ]
