# Generated by Django 2.2.7 on 2019-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_habitat_threats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat',
            name='average_temperature',
        ),
        migrations.RemoveField(
            model_name='habitat',
            name='yearly_average_rainfall',
        ),
        migrations.AddField(
            model_name='habitat',
            name='max_rainfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitat',
            name='max_temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitat',
            name='min_rainfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitat',
            name='min_temperature',
            field=models.IntegerField(default=0),
        ),
    ]
