# Generated by Django 2.2.7 on 2019-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_auto_20191113_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='max_rainfall',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='max_temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='min_rainfall',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='min_temperature',
            field=models.IntegerField(),
        ),
    ]
