# Generated by Django 2.2.7 on 2019-11-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_auto_20191113_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='threat',
            name='description',
        ),
        migrations.AddField(
            model_name='animal',
            name='descriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='animals', to='animals.Description'),
        ),
        migrations.AddField(
            model_name='threat',
            name='descriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='threats', to='animals.Description'),
        ),
    ]
