# Generated by Django 2.2.7 on 2019-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20191113_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat',
            name='description',
        ),
        migrations.AddField(
            model_name='habitat',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
