# Generated by Django 2.2.7 on 2019-11-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_auto_20191113_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptions', to='animals.Animal'),
        ),
    ]
