# Generated by Django 2.2.7 on 2019-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_description_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
