# Generated by Django 2.2.7 on 2019-11-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0020_auto_20191113_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptions', to='animals.Threat'),
        ),
    ]
