# Generated by Django 2.2.7 on 2019-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0022_auto_20191114_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='brief',
            field=models.CharField(default='', max_length=100),
        ),
    ]
