# Generated by Django 2.2.7 on 2019-11-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0023_description_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='brief',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='description',
            name='info',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='animals.Animal')),
                ('habitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='animals.Habitat')),
                ('threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='animals.Threat')),
            ],
        ),
    ]
