# Generated by Django 2.2.7 on 2019-11-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0025_auto_20191114_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='diet',
            field=models.CharField(choices=[('HE', 'Aquatic'), ('OM', 'Omnivore'), ('CA', 'Carnivore')], max_length=20),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='habitat_category',
            field=models.CharField(choices=[('AQ', 'Aquatic'), ('DE', 'Desert'), ('TU', 'Tundra'), ('FO', 'Forest'), ('GR', 'Grassland')], default='', max_length=20),
        ),
    ]
