# Generated by Django 2.2.7 on 2019-11-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0028_auto_20191115_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptions', to='animals.Habitat'),
        ),
    ]
