# Generated by Django 2.2.7 on 2019-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0029_description_habitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
