# Generated by Django 2.2.7 on 2019-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0030_auto_20191115_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='size_unit',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight_unit',
            field=models.CharField(default='', max_length=30),
        ),
    ]
