# Generated by Django 2.2.7 on 2019-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0033_auto_20191116_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(),
        ),
    ]
