# Generated by Django 2.2.7 on 2019-11-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0034_auto_20191116_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.FloatField(),
        ),
    ]
