# Generated by Django 2.2.7 on 2019-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0035_auto_20191116_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
