# Generated by Django 2.2.7 on 2019-11-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0037_auto_20191118_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='classification',
            new_name='classification_group',
        ),
    ]
